services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development
    networks:
      - mynetwork

  authenticator:
    build:
      context: ./authenticator
    ports:
      - "3000:3000"
    volumes:
      - ./authenticator:/app
    environment:
      - NODE_ENV=development
    networks:
      - mynetwork

networks:
  mynetwork:
