services:
  authenticator:
    build:
      context: ./authenticator
    ports:
      - "3000:3000"
      - "8000:8000"
    volumes:
      - ./authenticator:/app
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
